"""
bnirl.py
--------
Bayesian Non-parametric IRL (BNIRL) — Fixed-K=2 Gibbs sampler for subgoal
inference.

Algorithm
---------
Assumes each trajectory step is generated by either a latent subgoal or the
terminal goal (K=2 mixture). Alternates between:
  1. Sampling step assignments to subgoal vs. terminal goal.
  2. Sampling the subgoal location given the assigned steps.

After burn-in, the subgoal samples form a 2-D histogram over grid cells.
The mode of the post-burn-in samples is the predicted subgoal.

Reference
---------
Adapted from jupyter_demos/BNIRL/append_sections.py.
Key change: global GRID constant replaced with explicit (grid_rows, grid_cols).

Public API
----------
    run_bnirl(paths, layout, n_iter=500, burn_in=100, alpha=3.0, seed=42)
        -> (score_grid_display, predicted_json_coords)

Coordinate conventions
----------------------
- JSON coords : (col, row_from_top)  — row 0 = top of grid image
- MDP coords  : (x, y_mdp)           — y=0 = bottom row
- Internally, all positions are in MDP coords; score grid is flipped for display.
"""

import sys
from pathlib import Path

import numpy as np

# ── Path setup ────────────────────────────────────────────────────────────────
_ALGO_DIR = Path(__file__).resolve().parent
if str(_ALGO_DIR) not in sys.path:
    sys.path.insert(0, str(_ALGO_DIR))

from algorithms_util import to_mdp, to_json


# ── Gibbs sampler internals ───────────────────────────────────────────────────

def _step_likelihood(pos, next_pos, goal, alpha, grid_rows, grid_cols):
    """
    Softmax likelihood that an agent at `pos` steps to `next_pos` when
    heading toward `goal`.

    Uses a Manhattan-distance-based reward over valid neighbours, normalised
    with a softmax of temperature alpha.

    Parameters
    ----------
    pos, next_pos : (x, y_mdp) tuples
    goal          : (x, y_mdp) target cell
    alpha         : float — softmax temperature (higher = more peaked)
    grid_rows, grid_cols : int — grid dimensions in MDP coords

    Returns
    -------
    float — probability of taking the step pos → next_pos
    """
    px, py = int(pos[0]),      int(pos[1])
    nx, ny = int(next_pos[0]), int(next_pos[1])
    gx, gy = int(goal[0]),     int(goal[1])

    # Valid neighbours (cardinal moves within grid bounds)
    nbrs = [
        (px + dx, py + dy)
        for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]
        if 0 <= px + dx < grid_cols and 0 <= py + dy < grid_rows
    ]
    if not nbrs:
        return 1.0

    # Reward = negative Manhattan distance to goal
    scores = np.array(
        [alpha * (-abs(cx - gx) - abs(cy - gy)) for cx, cy in nbrs],
        dtype=float,
    )
    scores -= scores.max()   # numerical stability
    w = np.exp(scores)
    w /= w.sum()

    for i, (cx, cy) in enumerate(nbrs):
        if cx == nx and cy == ny:
            return float(w[i])
    return 1e-10   # next_pos not a valid neighbour


def _sample_assignments(steps, subgoal, terminal, alpha, rng, grid_rows, grid_cols):
    """
    Sample step-to-goal assignments for each consecutive pair in `steps`.

    Each step i is assigned to subgoal (0) or terminal (1) in proportion to
    the step likelihoods under each.

    Parameters
    ----------
    steps    : list of (x, y_mdp) — full position sequence
    subgoal  : (x, y_mdp) — current subgoal sample
    terminal : (x, y_mdp) — terminal/goal cell
    alpha    : float — likelihood temperature
    rng      : np.random.Generator
    grid_rows, grid_cols : int

    Returns
    -------
    np.ndarray of int, shape (len(steps)-1,) — 0=subgoal, 1=terminal
    """
    n   = len(steps) - 1
    sg  = tuple(int(x) for x in subgoal)
    tg  = tuple(int(x) for x in terminal)
    assignments = np.zeros(n, dtype=int)
    for i in range(n):
        ll_sg = _step_likelihood(steps[i], steps[i + 1], sg, alpha, grid_rows, grid_cols)
        ll_tg = _step_likelihood(steps[i], steps[i + 1], tg, alpha, grid_rows, grid_cols)
        total = ll_sg + ll_tg
        p_sg  = ll_sg / total if total > 1e-15 else 0.5
        assignments[i] = rng.choice(2, p=[p_sg, 1.0 - p_sg])
    return assignments


def _sample_subgoal(steps, assignments, rng, grid_rows, grid_cols):
    """
    Sample a new subgoal position given the current step assignments.

    Uses the median of the next-positions of steps assigned to the subgoal
    as a simple sampler (consistent with the original append_sections.py).

    Parameters
    ----------
    steps       : list of (x, y_mdp)
    assignments : np.ndarray — 0=subgoal, 1=terminal for each step
    rng         : np.random.Generator
    grid_rows, grid_cols : int

    Returns
    -------
    (x, y_mdp) — new subgoal sample
    """
    mask = (assignments == 0)
    if mask.sum() == 0:
        # No steps assigned to subgoal; sample uniformly
        return (int(rng.integers(0, grid_cols)), int(rng.integers(0, grid_rows)))

    ends = np.array(
        [[int(steps[i + 1][0]), int(steps[i + 1][1])]
         for i in range(len(assignments)) if assignments[i] == 0]
    )
    mx = int(np.clip(round(float(np.median(ends[:, 0]))), 0, grid_cols - 1))
    my = int(np.clip(round(float(np.median(ends[:, 1]))), 0, grid_rows - 1))
    return (mx, my)


def _run_gibbs(steps, terminal, n_iter, alpha, rng, grid_rows, grid_cols):
    """
    Run the Gibbs sampler for n_iter iterations.

    Parameters
    ----------
    steps    : list of (x, y_mdp) — concatenated position sequence
    terminal : (x, y_mdp) — terminal/goal cell
    n_iter   : int — total Gibbs iterations
    alpha    : float — step-likelihood temperature
    rng      : np.random.Generator
    grid_rows, grid_cols : int

    Returns
    -------
    np.ndarray, shape (n_iter, 2) — sampled subgoal (x, y_mdp) at each step
    """
    init = int(rng.integers(0, len(steps)))
    sg   = tuple(int(x) for x in steps[init])
    hist = np.zeros((n_iter, 2), dtype=int)
    for t in range(n_iter):
        asgn     = _sample_assignments(steps, sg, terminal, alpha, rng, grid_rows, grid_cols)
        sg       = _sample_subgoal(steps, asgn, rng, grid_rows, grid_cols)
        hist[t]  = sg
    return hist


# ── Main wrapper ──────────────────────────────────────────────────────────────

def run_bnirl(paths, layout, n_iter=500, burn_in=100, alpha=3.0, seed=42):
    """
    Fixed-K=2 BNIRL Gibbs sampler for subgoal inference.

    Concatenates all trajectory paths into a single position sequence, runs
    the Gibbs sampler, and builds a 2-D histogram of post-burn-in subgoal
    samples. The mode of the histogram is the predicted subgoal.

    Parameters
    ----------
    paths : list of list of (col, row_top)
        One or more trajectory paths in JSON coordinates.
    layout : dict
        Grid layout dict with keys: grid_layout, goal_pos, coin_pos,
        agent_start_pos.
    n_iter : int
        Total Gibbs iterations (including burn-in).
    burn_in : int
        Number of initial iterations to discard.
    alpha : float
        Step-likelihood softmax temperature.
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    score_grid_display : np.ndarray, shape (n_rows, n_cols)
        Post-burn-in sample count at each cell, indexed [row_top, col].
        Wall cells are NaN.
    predicted_json_coords : (col, row_top)
        Cell with the highest sample count (mode of posterior).
    """
    n_rows = len(layout["grid_layout"])
    n_cols = len(layout["grid_layout"][0])
    goal_j = tuple(layout["goal_pos"])
    goal_m = to_mdp(*goal_j, n_rows)

    # Concatenate all paths into a single MDP-coord position sequence
    steps = [
        to_mdp(col, rt, n_rows)
        for path in paths
        for col, rt in path
    ]

    if len(steps) < 2:
        return np.full((n_rows, n_cols), np.nan), goal_j

    rng  = np.random.default_rng(seed)
    hist = _run_gibbs(steps, goal_m, n_iter, alpha, rng, n_rows, n_cols)

    # Build 2-D histogram over post-burn-in samples, indexed [y_mdp, col]
    heat = np.zeros((n_rows, n_cols), dtype=float)
    for x, y in hist[burn_in:]:
        if 0 <= x < n_cols and 0 <= y < n_rows:
            heat[y, x] += 1

    # Flip y axis: MDP y=0 (bottom) → display row_top = n_rows-1
    score = heat[::-1].copy().astype(float)

    # Mask wall cells
    grid = layout["grid_layout"]
    for rt in range(n_rows):
        for col in range(n_cols):
            if grid[rt][col] == "#":
                score[rt, col] = np.nan

    if np.nanmax(score) == 0:
        return score, goal_j

    # Predicted = argmax excluding goal cell
    excl = score.copy()
    excl[goal_j[1], goal_j[0]] = np.nan
    idx  = int(np.nanargmax(excl))
    r_p, c_p = divmod(idx, n_cols)
    return score, (c_p, r_p)
